---
services:
  # TODO: Add proper service name
  ${SERVICE_NAME}:
    build:
      dockerfile: .devcontainer/Dockerfile
      target: dev
    volumes:
      # TODO: Add proper service folder name
      - ./${SERVICE_NAME}:/app
      - /app/node_modules/
